name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Quy trình sẽ tự chạy mỗi khi code được đẩy lên nhánh main

# Thiết lập các quyền để cấp cho GITHUB_TOKEN thực hiện deploy lên GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Sử dụng Node phiên bản 20 ổn định

      - name: Install dependencies
        run: npm install    # Cài đặt thư viện không cần lockfile

      - name: Build
        run: npm run build  # Đóng gói sản phẩm vào thư mục /dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'   # Đưa thư mục dist (chứa trang web hoàn chỉnh) lên Pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
